OUTPUT_FOLDER = 'OUTPUT_FOLDER'
MEDIA_FOLDER = 'MEDIA_FOLDER'
# Picture parameters
PREFIX_PIC = 'PREFIX_PIC'
ENDING_PIC = 'ENDING_PIC'
UPLOAD_FOLDER_PIC = 'UPLOAD_FOLDER_PIC'
LATEST_PIC_RES_Y = 'LATEST_PIC_RES_Y'
LATEST_PIC_RES_X = 'LATEST_PIC_RES_X'
# Video Settings
VIDEO_CAPTURE_INST = 'VC'
DURATION_VID = 'DURATION_VID'
VID_RES_X = 'VID_RES_X'
VID_RES_Y = 'VID_RES_Y'
SENSITIVITY = 'SENSITIVITY'
PREFIX_VID = 'PREFIX_VID'
VID_ENDINGS = 'VID_ENDINGS'
VID_FRAMES = 'VID_FRAMES'
UPLOAD_FOLDER_VID = 'UPLOAD_FOLDER_VID'
UPLOAD_FOLDER_VID_NO = 'UPLOAD_FOLDER_VID_NO'
SOUND_FORMAT = 'SOUND_FORMAT'
VID_FOURCC = 'VID_FOURCC'
VID_FORMAT = 'VID_FORMAT'
VID_LABEL_FORMAT = 'VID_LABEL_FORMAT'
# Replay settings
REPLAY_ENABLED = 'REPLAY_ENABLED'
REPLAY_INTERVAL = 'REPLAY_INTERVAL'
REPLAY_DAYS = 'REPLAY_DAYS'
FRAMES_PER_SEC_REPLAY = 'FRAMES_PER_SEC_REPLAY'
UPLOAD_FOLDER_REPLAY = 'UPLOAD_FOLDER_REPLAY'
REPLAY_LAST_STARTTIME = 'STARTTIME'
PREFIX_VID_REPLAY = 'PREFIX_VID_REPLAY'
# Server Upload parameters
NUM_RETRY_UPLOAD = 'NUM_RETRY_UPLOAD'
PAUSE_RETRY_UPLOAD = 'PAUSE_RETRY_UPLOAD'
SERVER_UPLOAD_ENABLED = 'SERVER_UPLOAD_ENABLED'
SERVER_UPLOAD = 'SERVER_UPLOAD'
FOLDER_UPLOAD = 'FOLDER_UPLOAD'
TIME_UPLOAD = 'TIME_UPLOAD'
UPLOAD_TIME_FORMAT = '%H:%M'

UPLOAD_FOLDER_PIC = 'UPLOAD_FOLDER_PIC'

# Statistic Export
ACTIVITY_LIST_END = 'ACTIVITY_LIST_END'
ACTIVITY_LIST_OUT = 'ACTIVITY_LIST_OUT'
ACTIVITY_LIST_END = 'ACTIVITY_LIST_END'
UPLOAD_FOLDER_CHART = 'UPLOAD_FOLDER_CHART'
FOLDER_CSV_FILE_OUTPUT = 'FOLDER_CSV_FILE_OUTPUT'
# database
SQLALCHEMY_DATABASE_URI = 'SQLALCHEMY_DATABASE_URI'

# settings Main screen
FIRST_VISIT = 'FIRST_VISIT'
DATE_EGG = 'DATE_EGG'
DATE_CHICK = 'DATE_CHICK'
DATE_LEAVE = 'DATE_LEAVE'
NAME_BIRD = 'NAME_BIRD'
UPLOAD_FOLDER_PERSONAS = 'UPLOAD_FOLDER_PERSONAS'

# group contig Entries
NEST_CONFIG = 'NEST_CONFIG'
REPLAY = 'REPLAY'
VIDEO = 'VIDEO'
SYSTEM = 'SYSTEM'
PICTURE = 'PICTURE'
SMB = 'SMB'
DATA = 'DATA'
# general settings
DATETIME_FORMAT = "%d.%m.%Y %H:%M:%S"
DATETIME_FORMATE_UI = '%Y-%m-%dT%H:%M:%S'
DATEFORMATE_FILE_SEL = '%Y-%m-%d'
TIME_FORMAT_FILE = 'TIME_FORMAT_FILE'
ROOT_PATH_APPLICATION = 'root_path'

# temperature sensors
WIREDATEI_TEMP_NEST = 'WIREDATEI_TEMP_NEST'
WIREDATEI_TEMP_OUT = 'WIREDATEI_TEMP_OUT'
