FOLDER_MEDIA = 'FOLDER_MEDIA'
FOLDER_PICTURES = 'FOLDER_PICTURES'
FOLDER_VIDEOS = 'FOLDER_VIDEOS'
FOLDER_VIDEOS_NO_DETECT = 'FOLDER_VIDEOS_NO_DETECT'
FOLDER_VIDEOS_DETECT = 'FOLDER_VIDEOS_DETECT'
FOLDER_REPLAY = 'FOLDER_REPLAY'
FOLDER_REPLAY_SCREENSHOT = 'FOLDER_REPLAY_SCREENSHOT'
FOLDER_REPLAY_VIDEOS = 'FOLDER_REPLAY_VIDEOS'
FOLDER_PERSONAS = 'FOLDER_PERSONAS'
# Picture parameters
PREFIX_PIC = 'PREFIX_PIC'
ENDING_PIC = 'ENDING_PIC'
LATEST_PIC_RES_Y = 'LATEST_PIC_RES_Y'
LATEST_PIC_RES_X = 'LATEST_PIC_RES_X'
# Video Settings
DURATION_VID = 'DURATION_VID'
VID_RES_X = 'VID_RES_X'
VID_RES_Y = 'VID_RES_Y'
SENSITIVITY = 'SENSITIVITY'
GRAYSCALE_ENABLED = 'GRAYSCALE_ENABLED'
PREFIX_VID = 'PREFIX_VID'
VID_FRAMES = 'VID_FRAMES'
VID_FORMAT = 'VID_FORMAT'
VID_LABEL_FORMAT = 'VID_LABEL_FORMAT'
# Replay settings
REPLAY_ENABLED = 'REPLAY_ENABLED'
REPLAY_INTERVAL = 'REPLAY_INTERVAL'
REPLAY_DAYS = 'REPLAY_DAYS'
REPLAY_LAST_RUN_SCREEN = 'REPLAY_LAST_RUN_SCREEN'
FRAMES_PER_SEC_REPLAY = 'FRAMES_PER_SEC_REPLAY'
REPLAY_LAST_STARTTIME = 'STARTTIME'
REPLAY_PREFIX_VID = 'REPLAY_PREFIX_VID'

VID_ANALYSER = 'VID_ANALYSER'
VID_ANALYSER_TIME_RUN = 'VID_ANALYSER_TIME_RUN'
VID_ANALYSER_FRAME_DISTANCE = 'VID_ANALYSER_FRAME_DISTANCE'
VID_ANALYSER_ENABLED = 'VID_ANALYSER_ENABLED'

# Server Upload parameters
NUM_RETRY_UPLOAD = 'NUM_RETRY_UPLOAD'
PAUSE_RETRY_UPLOAD = 'PAUSE_RETRY_UPLOAD'
SERVER_UPLOAD_ENABLED = 'SERVER_UPLOAD_ENABLED'

FILE_SHARE_ENABLED = 'FILE_SHARE_ENABLED'

FTP_ENABLED = 'FTP_ENABLED'
FTP_SERVER = 'FTP_SERVER'
FTP_PORT = 'FTP_PORT'
FTP_SHARE = 'FTP_SHARE'
FTP_USER = 'FTP_USER'
FTP_PASSWORD = 'FTP_PASSWORD'

NEXT_CLOUD_ENABLED = 'NEXT_CLOUD_ENABLED'
NEXT_CLOUD_SERVER = 'NEXT_CLOUD_SERVER'
NEXT_CLOUD_USER = 'NEXT_CLOUD_USER'
NEXT_CLOUD_PASSWORD = 'NEXT_CLOUD_PASSWORD'
NEXT_CLOUD_FOLDER = 'NEXT_CLOUD_FOLDER'

SMB_ENABLED = 'SMB_ENABLED'
SMB_SERVER = 'SMB_SERVER'
SMB_FOLDER = 'SMB_FOLDER'
SMB_USER = 'SMB_USER'
SMB_PASSWORD = 'SMB_PASSWORD'
SMB_SHARE = 'SMB_SHARE'

TIME_UPLOAD = 'TIME_UPLOAD'
UPLOAD_TIME_FORMAT = '%H:%M'

DELETE_AFTER_UPLOAD_ENABLED = 'DELETE_AFTER_UPLOAD_ENABLED'
DELETE_NO_DETECT_ENABLED = 'DELETE_NO_DETECT_ENABLED'
KEEP_FILE_LOCAL = 'KEEP_FILE_LOCAL'

# database
SQLALCHEMY_DATABASE_URI = 'SQLALCHEMY_DATABASE_URI'
EVENT_HANDLERS = 'EVENT_HANDLERS'
# settings Main screen
FIRST_VISIT = 'FIRST_VISIT'
DATE_EGG = 'DATE_EGG'
DATE_CHICK = 'DATE_CHICK'
DATE_LEAVE = 'DATE_LEAVE'
NAME_BIRD = 'NAME_BIRD'

# group contig Entries
NEST_CONFIG = 'NEST_CONFIG'
REPLAY = 'REPLAY'
VIDEO = 'VIDEO'
SYSTEM = 'SYSTEM'
KEY = ''
PICTURE = 'PICTURE'
SMB = 'SMB'
FTP = 'FTP'
NEXT_CLOUD = 'NEXT_CLOUD'
FILE_SHARE = 'FILE_SHARE'
DATA = 'DATA'
# general settings
DATETIME_FORMAT = "%d.%m.%Y %H:%M:%S"
DATETIME_FORMATE_UI = '%Y-%m-%dT%H:%M:%S'
DATEFORMATE_FILE_SEL = '%Y-%m-%d'
TIME_FORMAT_FILE = 'TIME_FORMAT_FILE'
ROOT_PATH_APPLICATION = 'root_path'
DB_SESSION = 'DB_SESSION'

#Logging
LOG_LEVEL = 'LOG_LEVEL'
LOG_FORMAT = 'LOG_FORMAT'
LOG_LOCATION = 'LOG_LOCATION'